# AIDungeonGenerator Configuration

# General Settings
settings:
  debug-mode: false
  language: en
  dungeon-per-biome: true
  min-distance-between-dungeons: 1000
  world-blacklist:
    - world_nether
    - world_the_end
