# AIDungeonGenerator Configuration

# General Settings
settings:
  debug-mode: false
  dungeon-per-biome: true
  min-distance-between-dungeons: 1000
  world-blacklist:
    - world_nether
    - world_the_end

# Generation Settings
generation:
  async:
    enabled: true
    tasks-per-tick: 2
    max-concurrent-generations: 3
  algorithm:
    room-size: 
      min: 5
      max: 15
    corridor-length:
      min: 3
      max: 10
    dungeon-size:
      small: 25
      medium: 40
      large: 60
    optimization-generations: 10

# Biome Theme Mappings
biome-themes:
  DESERT: "PYRAMID"
  DESERT_HILLS: "PYRAMID"
  BADLANDS: "MINESHAFT"
  FOREST: "RUINS"
  DARK_FOREST: "WITCH_HUT"
  PLAINS: "VILLAGE_RUINS"
  MOUNTAINS: "DWARVEN_HALLS"
  SAVANNA: "TRIBAL_SHRINE"
  TAIGA: "ICE_CASTLE"
  SWAMP: "SUNKEN_TEMPLE"
  JUNGLE: "TEMPLE"
  OCEAN: "UNDERWATER_RUINS"

# Dungeon Themes
themes:
  PYRAMID:
    primary-blocks:
      - SANDSTONE
      - SMOOTH_SANDSTONE
      - CUT_SANDSTONE
    accent-blocks:
      - GOLD_BLOCK
      - CHISELED_SANDSTONE
    floor-blocks:
      - SANDSTONE
      - SMOOTH_SANDSTONE
    ceiling-blocks:
      - SANDSTONE
      - SMOOTH_SANDSTONE
    light-blocks:
      - TORCH
      - LANTERN
    treasure-chance: 0.7
    traps:
      - ARROW
      - PIT
      - LAVA

  RUINS:
    primary-blocks:
      - COBBLESTONE
      - MOSSY_COBBLESTONE
      - STONE_BRICKS
    accent-blocks:
      - CRACKED_STONE_BRICKS
      - MOSSY_STONE_BRICKS
    floor-blocks:
      - COBBLESTONE
      - DIRT
      - GRAVEL
    ceiling-blocks:
      - COBBLESTONE
      - STONE_BRICKS
    light-blocks:
      - TORCH
    treasure-chance: 0.5
    traps:
      - ARROW
      - PIT
      - CAVE_IN
      
  MINESHAFT:
    primary-blocks:
      - OAK_PLANKS
      - SPRUCE_PLANKS
      - OAK_FENCE
    accent-blocks:
      - COBWEB
      - COAL_ORE
      - IRON_ORE
    floor-blocks:
      - DIRT
      - COARSE_DIRT
      - GRAVEL
    ceiling-blocks:
      - OAK_PLANKS
      - SPRUCE_PLANKS
    light-blocks:
      - TORCH
      - LANTERN
    treasure-chance: 0.6
    traps:
      - PIT
      - CAVE_IN
      - POISON_GAS
      
  DWARVEN_HALLS:
    primary-blocks:
      - STONE_BRICKS
      - POLISHED_ANDESITE
      - POLISHED_GRANITE
    accent-blocks:
      - GOLD_BLOCK
      - IRON_BLOCK
      - ANVIL
    floor-blocks:
      - POLISHED_ANDESITE
      - STONE_BRICKS
    ceiling-blocks:
      - STONE_BRICKS
      - POLISHED_GRANITE
    light-blocks:
      - LANTERN
      - TORCH
    treasure-chance: 0.7
    traps:
      - LAVA
      - PIT
      - FIRE
      
  ICE_CASTLE:
    primary-blocks:
      - PACKED_ICE
      - BLUE_ICE
      - ICE
    accent-blocks:
      - SNOW_BLOCK
      - BLUE_STAINED_GLASS
    floor-blocks:
      - PACKED_ICE
      - SNOW_BLOCK
    ceiling-blocks:
      - ICE
      - BLUE_ICE
    light-blocks:
      - SEA_LANTERN
      - SOUL_LANTERN
    treasure-chance: 0.6
    traps:
      - FREEZING
      - PIT
      - TELEPORTER
      
  UNDERWATER_RUINS:
    primary-blocks:
      - PRISMARINE
      - PRISMARINE_BRICKS
      - DARK_PRISMARINE
    accent-blocks:
      - SEA_LANTERN
      - CONDUIT
    floor-blocks:
      - PRISMARINE
      - SAND
      - GRAVEL
    ceiling-blocks:
      - PRISMARINE_BRICKS
      - DARK_PRISMARINE
    light-blocks:
      - SEA_LANTERN
      - GLOWSTONE
    treasure-chance: 0.8
    traps:
      - POISON_GAS
      - TELEPORTER
      - GUARDIAN_TRAP

  WITCH_HUT:
    primary-blocks:
      - DARK_OAK_PLANKS
      - DARK_OAK_LOG
      - STRIPPED_DARK_OAK_LOG
    accent-blocks:
      - CAULDRON
      - COBWEB
      - MUSHROOM_STEM
    floor-blocks:
      - DARK_OAK_PLANKS
      - MOSS_BLOCK
      - MOSSY_COBBLESTONE
    ceiling-blocks:
      - DARK_OAK_PLANKS
      - DARK_OAK_WOOD
    light-blocks:
      - SOUL_LANTERN
      - CANDLE
      - SOUL_TORCH
    treasure-chance: 0.65
    traps:
      - POISON_GAS
      - PIT
      - TELEPORTER

  VILLAGE_RUINS:
    primary-blocks:
      - COBBLESTONE
      - OAK_PLANKS
      - BRICKS
    accent-blocks:
      - FLOWER_POT
      - BOOKSHELF
      - CRAFTING_TABLE
    floor-blocks:
      - OAK_PLANKS
      - COBBLESTONE
      - COARSE_DIRT
    ceiling-blocks:
      - OAK_PLANKS
      - OAK_WOOD
    light-blocks:
      - LANTERN
      - TORCH
    treasure-chance: 0.55
    traps:
      - ARROW
      - PIT
      - CAVE_IN

  TRIBAL_SHRINE:
    primary-blocks:
      - TERRACOTTA
      - ACACIA_PLANKS
      - ACACIA_LOG
    accent-blocks:
      - ORANGE_TERRACOTTA
      - RED_TERRACOTTA
      - YELLOW_TERRACOTTA
    floor-blocks:
      - TERRACOTTA
      - RED_SAND
      - COARSE_DIRT
    ceiling-blocks:
      - ACACIA_PLANKS
      - TERRACOTTA
    light-blocks:
      - TORCH
      - FIRE
      - CAMPFIRE
    treasure-chance: 0.7
    traps:
      - FLAME_JET
      - ARROW
      - PIT

  SUNKEN_TEMPLE:
    primary-blocks:
      - MOSSY_STONE_BRICKS
      - MOSSY_COBBLESTONE
      - CRACKED_STONE_BRICKS
    accent-blocks:
      - LILY_PAD
      - VINES
      - CHISELED_STONE_BRICKS
    floor-blocks:
      - MOSSY_STONE_BRICKS
      - MOSS_BLOCK
      - MUD
    ceiling-blocks:
      - MOSSY_STONE_BRICKS
      - STONE_BRICKS
    light-blocks:
      - SHROOMLIGHT
      - SEA_PICKLE
      - SOUL_LANTERN
    treasure-chance: 0.75
    traps:
      - POISON_GAS
      - PIT
      - TELEPORTER

  TEMPLE:
    primary-blocks:
      - MOSSY_COBBLESTONE
      - MOSSY_STONE_BRICKS
      - JUNGLE_PLANKS
    accent-blocks:
      - CHISELED_STONE_BRICKS
      - GOLD_BLOCK
      - LAPIS_BLOCK
    floor-blocks:
      - MOSSY_STONE_BRICKS
      - MOSSY_COBBLESTONE
      - JUNGLE_PLANKS
    ceiling-blocks:
      - MOSSY_STONE_BRICKS
      - JUNGLE_PLANKS
    light-blocks:
      - LANTERN
      - TORCH
      - GLOWSTONE
    treasure-chance: 0.8
    traps:
      - ARROW
      - PIT
      - FLAME_JET
      - CAVE_IN

  NETHER_BASTION:
    primary-blocks:
      - BLACKSTONE
      - POLISHED_BLACKSTONE
      - GILDED_BLACKSTONE
    accent-blocks:
      - NETHER_GOLD_ORE
      - ANCIENT_DEBRIS
      - CHISELED_POLISHED_BLACKSTONE
    floor-blocks:
      - BLACKSTONE
      - SOUL_SOIL
      - POLISHED_BASALT
    ceiling-blocks:
      - POLISHED_BLACKSTONE
      - CRACKED_POLISHED_BLACKSTONE_BRICKS
    light-blocks:
      - SHROOMLIGHT
      - LANTERN
      - SOUL_FIRE
    treasure-chance: 0.85
    traps:
      - FLAME_JET
      - LAVA
      - TELEPORTER

  CRYSTALLINE_CAVERN:
    primary-blocks:
      - DEEPSLATE
      - TUFF
      - CALCITE
    accent-blocks:
      - AMETHYST_BLOCK
      - BUDDING_AMETHYST
      - PURPLE_STAINED_GLASS
    floor-blocks:
      - SMOOTH_BASALT
      - CALCITE
      - AMETHYST_BLOCK
    ceiling-blocks:
      - TUFF
      - DEEPSLATE
      - CALCITE
    light-blocks:
      - AMETHYST_CLUSTER
      - SEA_LANTERN
      - END_ROD
    treasure-chance: 0.9
    traps:
      - TELEPORTER
      - FREEZING
      - ARROW

  ANCIENT_LIBRARY:
    primary-blocks:
      - BOOKSHELF
      - DARK_OAK_PLANKS
      - DEEPSLATE_BRICKS
    accent-blocks:
      - LECTERN
      - ENCHANTING_TABLE
      - CHISELED_BOOKSHELF
    floor-blocks:
      - DARK_OAK_PLANKS
      - SPRUCE_PLANKS
      - POLISHED_DEEPSLATE
    ceiling-blocks:
      - DARK_OAK_PLANKS
      - SPRUCE_PLANKS
    light-blocks:
      - CANDLE
      - LANTERN
      - END_ROD
    treasure-chance: 0.75
    traps:
      - TELEPORTER
      - POISON_GAS
      - ARROW

  CORAL_REEF_RUINS:
    primary-blocks:
      - BRAIN_CORAL_BLOCK
      - TUBE_CORAL_BLOCK
      - FIRE_CORAL_BLOCK
    accent-blocks:
      - HORN_CORAL_BLOCK
      - BUBBLE_CORAL_BLOCK
      - DEAD_BRAIN_CORAL_BLOCK
    floor-blocks:
      - SAND
      - PRISMARINE
      - DEAD_BRAIN_CORAL_BLOCK
    ceiling-blocks:
      - DEAD_TUBE_CORAL_BLOCK
      - DEAD_HORN_CORAL_BLOCK
      - PRISMARINE
    light-blocks:
      - SEA_LANTERN
      - GLOWSTONE
    treasure-chance: 0.8
    traps:
      - GUARDIAN_TRAP
      - TELEPORTER
      - POISON_GAS

  SCULK_DUNGEON:
    primary-blocks:
      - DEEPSLATE_TILES
      - DEEPSLATE_BRICKS
      - REINFORCED_DEEPSLATE
    accent-blocks:
      - SCULK
      - SCULK_SENSOR
      - SCULK_CATALYST
    floor-blocks:
      - SCULK
      - DEEPSLATE_TILES
      - DEEPSLATE
    ceiling-blocks:
      - DEEPSLATE_TILES
      - REINFORCED_DEEPSLATE
    light-blocks:
      - SCULK_CATALYST
      - SOUL_LANTERN
    treasure-chance: 0.95
    traps:
      - WARDEN_SUMMON
      - TELEPORTER
      - SCULK_SHRIEKER

# Trap Settings
traps:
  enabled: true
  cooldown: 60
  difficulty: 
    easy: 0.3   # 30% damage multiplier
    normal: 1.0 # normal damage
    hard: 1.5   # 50% more damage
  types:
    ARROW:
      enabled: true
      damage: 4.0
    PIT:
      enabled: true
      depth: 4
      restore-time: 15
    LAVA:
      enabled: true
      duration: 10
    POISON_GAS:
      enabled: true
      duration: 10
      radius: 3
    CAVE_IN:
      enabled: true
      damage: 6.0
      restore-time: 30
    FLAME_JET:
      enabled: true
      duration: 5
      fire-ticks: 100
    TELEPORTER:
      enabled: true
      min-distance: 10
      max-distance: 30
    FREEZING:
      enabled: true
      duration: 10
      slow-level: 3
    WARDEN_SUMMON:
      enabled: true
      summon_chance: 0.7
      warning_sounds: 3
      despawn_time: 120
    SCULK_SHRIEKER:
      enabled: true
      shriek_count: 3
      radius: 5
      cooldown: 10

# Mob Settings
mobs:
  enabled: true
  difficulty-multiplier: 1.0
  elite:
    chance: 0.1
    health-multiplier: 2.0
    damage-multiplier: 1.5
    drop-multiplier: 2.0
  equipment:
    enabled: true
    drop-chance: 0.03
    elite-drop-chance: 0.08
  
# Discovery Settings
discovery:
  enable-compass: true
  show-on-map: true
  discovery-radius: 100
  hint-message: true
  
# Rewards
rewards:
  enable: true
  common-items:
    - IRON_INGOT:5
    - GOLD_INGOT:3
    - BREAD:10
  rare-items:
    - DIAMOND:2
    - EMERALD:3
    - ENCHANTED_BOOK:1
  legendary-items:
    - NETHERITE_INGOT:1
    - TRIDENT:1
    - ELYTRA:1
  custom-items:
    - name: "Ancient Sword"
      material: DIAMOND_SWORD
      enchantments:
        - SHARPNESS:5
        - FIRE_ASPECT:2
      chance: 0.1# AIDungeonGenerator Configuration

# General Settings
settings:
  debug-mode: false
  dungeon-per-biome: true
  min-distance-between-dungeons: 1000
  world-blacklist:
    - world_nether
    - world_the_end

# Generation Settings
generation:
  async:
    enabled: true
    tasks-per-tick: 2
    max-concurrent-generations: 3
  algorithm:
    room-size: 
      min: 5
      max: 15
    corridor-length:
      min: 3
      max: 10
    dungeon-size:
      small: 25
      medium: 40
      large: 60
    optimization-generations: 10

# Biome Theme Mappings
biome-themes:
  DESERT: "PYRAMID"
  DESERT_HILLS: "PYRAMID"
  BADLANDS: "MINESHAFT"
  FOREST: "RUINS"
  DARK_FOREST: "WITCH_HUT"
  PLAINS: "VILLAGE_RUINS"
  MOUNTAINS: "DWARVEN_HALLS"
  SAVANNA: "TRIBAL_SHRINE"
  TAIGA: "ICE_CASTLE"
  SWAMP: "SUNKEN_TEMPLE"
  JUNGLE: "TEMPLE"
  OCEAN: "UNDERWATER_RUINS"

# Dungeon Themes
themes:
  PYRAMID:
    primary-blocks:
      - SANDSTONE
      - SMOOTH_SANDSTONE
      - CUT_SANDSTONE
    accent-blocks:
      - GOLD_BLOCK
      - CHISELED_SANDSTONE
    floor-blocks:
      - SANDSTONE
      - SMOOTH_SANDSTONE
    ceiling-blocks:
      - SANDSTONE
      - SMOOTH_SANDSTONE
    light-blocks:
      - TORCH
      - LANTERN
    treasure-chance: 0.7
    traps:
      - ARROW
      - PIT
      - LAVA

  RUINS:
    primary-blocks:
      - COBBLESTONE
      - MOSSY_COBBLESTONE
      - STONE_BRICKS
    accent-blocks:
      - CRACKED_STONE_BRICKS
      - MOSSY_STONE_BRICKS
    floor-blocks:
      - COBBLESTONE
      - DIRT
      - GRAVEL
    ceiling-blocks:
      - COBBLESTONE
      - STONE_BRICKS
    light-blocks:
      - TORCH
    treasure-chance: 0.5
    traps:
      - ARROW
      - PIT
      - CAVE_IN

# Discovery Settings
discovery:
  enable-compass: true
  show-on-map: true
  discovery-radius: 100
  hint-message: true
  
# Rewards
rewards:
  enable: true
  common-items:
    - IRON_INGOT:5
    - GOLD_INGOT:3
    - BREAD:10
  rare-items:
    - DIAMOND:2
    - EMERALD:3
    - ENCHANTED_BOOK:1
  legendary-items:
    - NETHERITE_INGOT:1
    - TRIDENT:1
    - ELYTRA:1
  custom-items:
    - name: "Ancient Sword"
      material: DIAMOND_SWORD
      enchantments:
        - SHARPNESS:5
        - FIRE_ASPECT:2
      chance: 0.1

# Quest System Configuration

quests:
  enabled: true
  max_quests_per_player: 5
  show_claimed: false
  
  # Quest Templates
  templates:
    boss_slayer:
      name: Boss Slayer
      description: Defeat the dungeon boss to claim your reward
      type: KILL
      required_amount: 1
      target_entity: BOSS
      reward_commands:
        - give %player% diamond 5
        - xp add %player% 500
      reward_messages:
        - You have defeated the dungeon boss!
        - The cursed spirits can now rest.
      reward_items:
        - DIAMOND:5
        - EXPERIENCE_BOTTLE:10
        
    treasure_hunter:
      name: Treasure Hunter
      description: Collect the lost artifacts scattered throughout the dungeon
      type: COLLECT
      required_amount: 3
      target_item: EMERALD
      reward_commands:
        - give %player% gold_ingot 10
        - xp add %player% 300
      reward_messages:
        - You have collected all the lost artifacts!
        - Your archaeological skills are impressive.
      reward_items:
        - GOLD_INGOT:10
        - ENCHANTED_BOOK:1
        
    dungeon_explorer:
      name: Dungeon Explorer
      description: Discover the hidden treasure chambers of the dungeon
      type: EXPLORE
      required_amount: 2
      reward_commands:
        - give %player% iron_ingot 15
        - xp add %player% 200
      reward_messages:
        - You have explored the dungeon thoroughly!
        - Your cartography skills are impressive.
      reward_items:
        - MAP:1
        - COMPASS:1
        - IRON_INGOT:15
        
    monster_hunter:
      name: Monster Hunter
      description: Cleanse the dungeon of its monstrous inhabitants
      type: KILL
      required_amount: 15
      target_entity: ZOMBIE
      reward_commands:
        - give %player% experience_bottle 5
        - xp add %player% 250
      reward_messages:
        - You have cleansed the dungeon of monsters!
        - The dungeon is now safer thanks to your efforts.
      reward_items:
        - EXPERIENCE_BOTTLE:5
        - GOLDEN_APPLE:2
        
    arcane_collector:
      name: Arcane Collector
      description: Collect magical essence crystals from the dungeon
      type: COLLECT
      required_amount: 5
      target_item: AMETHYST_SHARD
      reward_commands:
        - give %player% glowstone 10
        - xp add %player% 350
      reward_messages:
        - You have collected all the magical essence crystals!
        - Your understanding of the arcane has increased.
      reward_items:
        - EXPERIENCE_BOTTLE:7
        - ENCHANTED_BOOK:1
        - GLOWSTONE:10
        
  # Biome-specific quests
  biome_quests:
    DESERT:
      - boss_slayer
      - treasure_hunter
    FOREST:
      - monster_hunter
      - dungeon_explorer
    MOUNTAINS:
      - boss_slayer
      - arcane_collector
    OCEAN:
      - treasure_hunter
      - dungeon_explorer
    default:
      - monster_hunter
      - boss_slayer
