name: AIDungeonGenerator
version: '${project.version}'
main: com.ubivismedia.aidungeon.AIDungeonGenerator
api-version: '1.19'
authors: [YourName]
description: An AI-powered dungeon generator for Minecraft
commands:
  aidungeon:
    description: Main command for AI Dungeon Generator
    usage: /aidungeon [generate|info|reload]
    aliases: [aid, dungeon]
    permission: aidungeon.admin
permissions:
  aidungeon.admin:
    description: Allows administration of AI Dungeon Generator
    default: op
  aidungeon.discover:
    description: Allows players to discover dungeons
    default: true
